name: food_ai_app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  exif: ^3.3.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  image: ^4.2.0
  image_picker: ^1.0.7
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sembast: ^3.7.2
  sembast_web: ^2.4.1
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/themes/theme_clean.json
    - assets/themes/theme_warm.json
    - assets/themes/theme_green.json
    - assets/themes/theme_pink.json
    - assets/plates/
    - assets/icons/favicon.png
    - assets/icons/Icon-192.png
    - assets/icons/Icon-512.png
